create VIEW public.vw_decisions
AS SELECT d.id,
    d.decision_id,
    d.file_name,
    d.url_official_publication,
    d.language_metadata,
    d.court_ecli_code,
    d.decision_type_ecli_code,
    d.decision_date,
    d.versions,
    d.url_pdf,
    d.rol_number,
    d."case",
    d.chamber,
    d.field_of_law,
    d.opinion_public_attorney,
    d.precedent,
    d.cited_in,
    d.see_more_recently,
    d.preceded_by,
    d.followed_by,
    d.rectification,
    d.related_case,
    d.created_at,
    d.updated_at,
    d.source,
    d.jurisdiction,
    d.citing,
    c.courtfr,
    c.courtnl,
    c.category AS court_category,
    dt.decision_type_fr,
    dt.decision_type_nl,
    d.micro_summary,
    d.citation_reference,
    d.facts,
    d.court_order,
    COALESCE(d.custom_keywords, d.custom_keywords_s, ARRAY[]::text[]::character varying[]) AS keywords
FROM decisions1 d
    LEFT JOIN courts c ON d.court_ecli_code::text = c.id::text
    LEFT JOIN decision_types dt ON d.decision_type_ecli_code::text = dt.decisiontypeeclicode::text;